### ISSUE TITLE
TODO 18/10/23

### ISSUE THREAD

**Issue by unlimblue** [unlimblue/turcnn#3]
- [ ] optimize dataset resize_ op 
- [ ] merge data prepare op
- [ ] abstract deploy framework
